export const data = [null, null,
    {
        title: '07:00 AM',
        hour: true,
        halfHour: false,
        quarter: false,
    },
    {
        title: '07:15 AM',
        hour: false,
        halfHour: false,
        quarter: true,
    },
    {
        title: '07:30 AM',
        hour: false,
        halfHour: true,
        quarter: false,
    },
    {
        title: '07:45 AM',
        hour: false,
        halfHour: false,
        quarter: true,
    },
    {
        title: '08:00 AM',
        hour: true,
        halfHour: false,
        quarter: false,
    },
    {
        title: '08:15 AM',
        hour: false,
        halfHour: false,
        quarter: true,
    },
    {
        title: '08:30 AM',
        hour: false,
        halfHour: true,
        quarter: false,
    },
    {
        title: '08:45 AM',
        hour: false,
        halfHour: false,
        quarter: true,
    },
    {
        title: '09:00 AM',
        hour: true,
        halfHour: false,
        quarter: false,
    },
    {
        title: '09:15 AM',
        hour: false,
        halfHour: false,
        quarter: true,
    },
    {
        title: '09:30 AM',
        hour: false,
        halfHour: true,
        quarter: false,
    },
    {
        title: '09:45 AM',
        hour: false,
        halfHour: false,
        quarter: true,
    },
    {
        title: '10:00 AM',
        hour: true,
        halfHour: false,
        quarter: false,
    },
    {
        title: '10:15 AM',
        hour: false,
        halfHour: false,
        quarter: true,
    },
    {
        title: '10:30 AM',
        hour: false,
        halfHour: true,
        quarter: false,
    },
    {
        title: '10:45 AM',
        hour: false,
        halfHour: false,
        quarter: true,
    },
    {
        title: '11:00 AM',
        hour: true,
        halfHour: false,
        quarter: false,
    },
    {
        title: '11:15 AM',
        hour: false,
        halfHour: false,
        quarter: true,
    },
    {
        title: '11:30 AM',
        hour: false,
        halfHour: true,
        quarter: false,
    },
    {
        title: '11:45 AM',
        hour: false,
        halfHour: false,
        quarter: true,
    },
    {
        title: '12:00 PM',
        hour: true,
        halfHour: false,
        quarter: false,
    },
    {
        title: '12:15 PM',
        hour: false,
        halfHour: false,
        quarter: true,
    },
    {
        title: '12:30 PM',
        hour: false,
        halfHour: true,
        quarter: false,
    },
    {
        title: '12:45 PM',
        hour: false,
        halfHour: false,
        quarter: true,
    },
    {
        title: '01:00 PM',
        hour: true,
        halfHour: false,
        quarter: false,
    },
    {
        title: '01:15 PM',
        hour: false,
        halfHour: false,
        quarter: true,
    },
    {
        title: '01:30 PM',
        hour: false,
        halfHour: true,
        quarter: false,
    },
    {
        title: '01:45 PM',
        hour: false,
        halfHour: false,
        quarter: true,
    },
]