# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dribble' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!
   pod 'Firebase/Core'
   pod 'Firebase/Auth'
   pod 'Firebase/Messaging'

  # Pods for Dribble

  target 'Dribble-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DribbleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Dribble-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Dribble-tvOS

  

end
