# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dribble' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Firebase/Core'
   pod 'Firebase/Auth'
   pod 'Firebase/Messaging'
   # pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'


  # Pods for Dribble

  target 'Dribble-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    # pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

    # pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

    #pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

    #pod 'RNSVG', :path => '../node_modules/react-native-svg'

    pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

    pod 'RNFBCrashlytics', :path => '../node_modules/@react-native-firebase/crashlytics'

    pod 'RNFBAnalytics', :path => '../node_modules/@react-native-firebase/analytics'

    pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

    pod 'react-native-branch', :path => '../node_modules/react-native-branch'

    pod 'react-native-webview', :path => '../node_modules/react-native-webview'

    pod 'RCTYouTube', :path => '../node_modules/react-native-youtube'

    pod 'RNShare', :path => '../node_modules/react-native-share'

    pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

    pod 'RNPinchZoomImage', :path => '../node_modules/react-native-pinch-zoom-image'

  end

  target 'DribbleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Dribble-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Dribble-tvOS

 end
